version: '3.3'

services:
  twitch-greetings:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../../src/main/resources/private_config.json:/project/private_config.json:ro
#    ports:
#      - 96:96
    restart: unless-stopped
