version: '3.3'

services:
#  twitch-greetings:
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    environment:
#      - CONFIG-FILE:/project/config.json
#    volumes:
#      - ../src/main/resources/private_config.json:/project/config.json:ro
##    ports:
##      - 96:96
#    restart: unless-stopped
  twitch-greetings2:
    image: wareagledocker/chat-greetings:latest
    environment:
      - CONFIG-FILE:/project/config.json
    volumes:
      - ../src/main/resources/private_config.json:/project/config.json:ro
    restart: unless-stopped
