version: '3.3'

services:
  twitch-greetings:
    image: wareagledocker/twitch-greetings:latest
    environment:
      - CONFIG_FILE:/project/config.json
    volumes:
      - ../src/main/resources/private_config.json:/project/config.json:ro
    restart: no
#    restart: unless-stopped
